AllCops:
  Includes:
    - metadata.rb
    - Gemfile
    - attributes/**
    - providers/**
    - resources/**
  Excludes:
    - recipes/**
    - spec/**

# UTF-8 headers not generally in these files
Encoding:
  Exclude:
    - metadata.rb
    - Gemfile

# ignore long lines
LineLength:
  Enabled: false

# Allow small arrays before forcing  %w or %W
WordArray:
  MinSize: 3

# TODO(galstom21)
# The rescue exception statements in providers/**.rb need to be modified,
# to rescue specific exceptions.
RescueException:
  Enabled: false
